title: Physical Comp. w/ Arduino
description: Hands-On Introduction to Physical Computing with Arduino course website
theme: just-the-docs
color_scheme: customRed

url: https://gocivici.github.io/ID7219

aux_links:
  "Course Repository":
    - "https://github.com/gocivici/ID7219"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/gocivici/ID7219" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately